environment:
  api_token:
    secure: JzM3ABvKVujItxRGcbP0JaWZaNnNvtzN+vnt4qaZfBk=
    
shallow_clone: true

configuration: Release

before_build:
- nuget restore

# package Web Application project for Web Deploy
build:
  verbosity: minimal
  publish_wap: true

test: off
  
deploy_script:
- ps: Start-AppveyorBuild -ApiKey $env:api_token -ProjectSlug deploy-project -EnvironmentVariables @{ "deploy_version" = $env:appveyor_build_version }
